version: '3'

services:
  app:
    image: python:3.6-alpine
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
